apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth
  labels:
    app.kubernetes.io/name: auth
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: board-api
  labels:
    app.kubernetes.io/name: board-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: board-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: board-worker
  labels:
    app.kubernetes.io/name: board-worker
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: board-worker
